import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  guideSidebar: [
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'documentation/Get Started/Overview',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'documentation/Get Started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Trade',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'documentation/Trade/Overview',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'documentation/Trade',
        },
      ],
    },
    {
      type: 'category',
      label: 'Invest & Devest',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'documentation/Invest&Devest/Overview',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'documentation/Invest&Devest',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tokenomics',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'documentation/Tokenomics/Overview',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'documentation/Tokenomics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Community',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'documentation/Community/Overview',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'documentation/Community',
        },
      ],
    },
  ],
  // Public Sale：左侧自动列出 articles/publicsale 目录下所有文档
  publicsaleSidebar: [
    {
      type: 'autogenerated',
      dirName: 'articles/publicsale',
    },
  ],
  articlesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'articles',
    },
  ],

  // 其他文档区可按同样方式扩展
  knowledgeSidebar: [
    {
      type: 'autogenerated',
      dirName: 'knowledge',
    },
  ],
  communitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'community',
    },
  ],
};

export default sidebars;
